export enum ProjectStage {
    PLANNING = 'PLANNING',
    DESIGN = 'DESIGN',
    DEVELOPMENT = 'DEVELOPMENT',
    INTEGRATION = 'INTEGRATION',
    DEPLOYMENT = 'DEPLOYMENT',
    TESTING = 'TESTING',
    MAINTENANCE = 'MAINTENANCE',
    SUPPORT = 'SUPPORT',
    CANCELED = 'CANCELED',
    COMPLETED = 'COMPLETED',
  }