export enum ProjectStatus {
    WAITING_FOR_APPROVE = 'WAITING_FOR_APPROVE',
    APPROVED = 'APPROVED',
    PAYMENT_DUE = 'PAYMENT_DUE',
    IN_PROGRESS = 'IN_PROGRESS',
    CANCELED = 'CANCELED',
    COMPLETED = 'COMPLETED',
  }